/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exercise.JcF_2.Sesi5;

import exercise.JcF_2.Sesi4.FrameDapurHome;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author WH
 */
public class FrameRegistrasion extends javax.swing.JFrame {

    String folderImage = "D:/java/exercise/src/exercise/jcf_2/Sesi5/Image/";
    public FrameRegistrasion() {
        initComponents();
    }

    private String inisialProvider(String noHpIn) {
        String[][] providerTelp = {
            {"0811", "Hallo"}, {"0812", "Simpati"}, {"0813", "Simpati"},
            {"0821", "Simpati"}, {"0822", "Simpati"}, {"0852", "AS"},
            {"0853", "AS"}, {"0823", "AS"}, {"0851", "AS"}, {"0814", "Indosat"},
            {"0815", "matrix"}, {"0816", "matrix"}, {"0855", "Matrix"},
            {"0856", "IM3"}, {"0857", "IM3"}, {"0858", "Mentari"},
            {"0817", "XL"}, {"0818", "XL"}, {"0819", "XL"}, {"0859", "XL"},
            {"0877", "XL"}, {"0878", "XL"}, {"0838", "AXIS"}, {"0831", "AXIS"}, 
            {"0832", "AXIS"}, {"0833", "AXIS"}, {"0895", "Three"},
            {"0896", "Three"}, {"0897", "Three"}, {"0898", "Three"}, 
            {"0899", "Three"}, {"0881", "SmartFren"}, {"0882", "SmartFren"}, 
            {"0883", "SmartFren"}, {"0884", "SmartFren"}, {"0885", "SmartFren"},
            {"0886", "SmartFren"}, {"0887", "SmartFren"}, {"0888", "SmartFren"},
            {"0889", "SmartFren"},
        };

        for (byte nn = 0; nn <= providerTelp.length; nn++) {
            if (providerTelp[nn][0].equals(noHpIn)) {
                return (providerTelp[nn][1]);
            }
        }
        //folderImage+"images_1.jpg")
        //labelPhoneNumber.setIcon(new ImageIcon(folderImage+"images_1.jpg"));
        
        return ("No Provider");
    }

    /**
     * Creates new form FrameDapurLogin
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelImage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFieldUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textFieldPassword = new javax.swing.JTextField();
        buttonLogin = new javax.swing.JButton();
        labelPhoneNumber = new javax.swing.JLabel();
        textFieldPhoneNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textFieldMinimumOrder = new javax.swing.JTextField();
        labelProvider = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exercise/JcF_2/Sesi4/image/10266-man-cook-icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelImage)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(labelImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cridentials"));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setText("Username : ");

        textFieldUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldUserNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldUserNameFocusLost(evt);
            }
        });
        textFieldUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldUserNameKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setText("Password : ");

        textFieldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldPasswordFocusLost(evt);
            }
        });
        textFieldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldPasswordKeyTyped(evt);
            }
        });

        buttonLogin.setMnemonic('S');
        buttonLogin.setText("Save");
        buttonLogin.setEnabled(false);
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        labelPhoneNumber.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labelPhoneNumber.setText("Phone number :");

        textFieldPhoneNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldPhoneNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldPhoneNumberFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setText("Minimum order :");

        textFieldMinimumOrder.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldMinimumOrderFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldMinimumOrderFocusLost(evt);
            }
        });

        labelProvider.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelProvider.setText("...");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldMinimumOrder)
                    .addComponent(textFieldUserName)
                    .addComponent(textFieldPassword)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(buttonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(textFieldPhoneNumber)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelPhoneNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                        .addComponent(labelProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPhoneNumber)
                    .addComponent(labelProvider))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldMinimumOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        if (textFieldUserName.getText().isEmpty()) {
            textFieldUserName.requestFocus();
        } else {
            if (!checkUserId(textFieldUserName)) {
                textFieldUserName.requestFocus();
            } else {
                if (textFieldPassword.getText().isEmpty()) {
                    textFieldPassword.requestFocus();
                } else {
                    if (checkPassWord(textFieldPassword)) {
                        JOptionPane.showMessageDialog(this, "Anda masuk ke menu berikutnya");
                    } else {
                        textFieldPassword.requestFocus();
                    }
                }
            }
        }
        
        

        /*FrameDapurHome frame = new FrameDapurHome(this);
        frame.setVisible(true);
        this.setVisible(false);
        */

    }//GEN-LAST:event_buttonLoginActionPerformed

    private void textFieldUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldUserNameFocusGained
        textFieldUserName.setBackground(Color.yellow);
    }//GEN-LAST:event_textFieldUserNameFocusGained

    private void textFieldPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPasswordFocusGained
        textFieldPassword.setBackground(Color.yellow);
    }//GEN-LAST:event_textFieldPasswordFocusGained

    private void textFieldUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldUserNameFocusLost
        textFieldUserName.setBackground(null);
    }//GEN-LAST:event_textFieldUserNameFocusLost

    private boolean checkUserId(JTextField textFieldIn) {
        byte huruf = 0;
        byte other = 0;
        char[] digits = textFieldIn.getText().toCharArray();
        for (byte nn = 0; nn < textFieldIn.getText().length(); nn++) {
            if (Character.isLetter(digits[nn])) {
                huruf++;
            } else {
                other++;
            }
        }

        if (other > 0) {
            JOptionPane.showMessageDialog(this, "UserId harus terdiri dari huruf");
        } else {
            if (huruf >= 8) {
                return (true);
            } else {

                JOptionPane.showMessageDialog(this, "UserId harus terdiri dari minimal 8 huruf");
            }
        }
        return (false);
    }

    private void textFieldPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPasswordFocusLost
        textFieldPassword.setBackground(null);
    }//GEN-LAST:event_textFieldPasswordFocusLost

    private boolean checkPassWord(JTextField textFieldIn) {
        byte hurufKecil = 0;
        byte hurufBesar = 0;
        byte angka = 0;

        char[] digits = textFieldIn.getText().toCharArray();
        for (byte nn = 0; nn < textFieldIn.getText().length(); nn++) {
            if (Character.isLetter(digits[nn])) {
                if (Character.isLowerCase(digits[nn])) {
                    hurufKecil++;
                } else {
                    hurufBesar++;
                }
            } else {
                angka++;
            }
        }
        if (hurufKecil >= 3) {
            if (hurufBesar >= 1) {
                if (hurufKecil + hurufBesar >= 8) {
                    if (angka == 1) {
                        return (true);
                    } else {
                        JOptionPane.showMessageDialog(this, "Password harus terdiri minimal 1 digit angka");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Password harus terdiri minimal 8 digit huruf");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Password harus terdiri minimal 1 digit huruf kapital");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Password harus terdiri minimal 3 digit huruf kecil");
        }
        return (false);
    }

    private void textFieldUserNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldUserNameKeyTyped
        toggleButtonLogin();
    }//GEN-LAST:event_textFieldUserNameKeyTyped

    private void textFieldPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldPasswordKeyTyped
        toggleButtonLogin();
    }//GEN-LAST:event_textFieldPasswordKeyTyped

    private void textFieldPhoneNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPhoneNumberFocusGained
        textFieldPhoneNumber.setBackground(Color.yellow);
    }//GEN-LAST:event_textFieldPhoneNumberFocusGained

    private void textFieldMinimumOrderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldMinimumOrderFocusGained
        textFieldMinimumOrder.setBackground(Color.yellow);
    }//GEN-LAST:event_textFieldMinimumOrderFocusGained

    private void textFieldPhoneNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldPhoneNumberFocusLost
        textFieldPhoneNumber.setBackground(null);
        labelProvider.setText(inisialProvider(textFieldPhoneNumber.getText().substring(0, 4)));  
    }//GEN-LAST:event_textFieldPhoneNumberFocusLost
  
    private void textFieldMinimumOrderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldMinimumOrderFocusLost
        textFieldMinimumOrder.setBackground(null);
    }//GEN-LAST:event_textFieldMinimumOrderFocusLost

    private void toggleButtonLogin() {
        // klu kosong button login disable
        if (isEmpty(textFieldUserName) && isEmpty(textFieldPassword)) {
            buttonLogin.setEnabled(false);
        } else {
            buttonLogin.setEnabled(true);
        }
    }

    private boolean isEmpty(JTextField compIn) {
        return !(compIn.getText().length() > 1);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRegistrasion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRegistrasion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRegistrasion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRegistrasion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRegistrasion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelPhoneNumber;
    private javax.swing.JLabel labelProvider;
    private javax.swing.JTextField textFieldMinimumOrder;
    private javax.swing.JTextField textFieldPassword;
    private javax.swing.JTextField textFieldPhoneNumber;
    private javax.swing.JTextField textFieldUserName;
    // End of variables declaration//GEN-END:variables
}
